POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzdHVydW5lbiIsImlkIjoiNjAyZTc0MTMwYjk3ZDE0ZWI0MjkxNmZhIiwiaWF0IjoxNjEzNjU4NjcyfQ.1clALghS9ggg6G8VN9d3-jhoNYqWYH9jOYUPjHLTXfA

{
"title": "Antin toinen frontend blogi",
"author": "Franz Kafka",
"url": "http//:urliii.url",
"likes": 2
}