PUT http://localhost:3001/api/blogs/606461da9ca558c730fbe909
content-type: application/json

{
"title": "PAIVITETTY BLOGI",
"author": "Paivettynyt PAtunen",
"url": "http//:urliii.url",
"likes": 100,
"comments":"muuta"
}